#!/usr/bin/python3
from sys import argv


def factorize(num):
    i = 2
    while (num % i != 0 and i <= num):
        i += 1
    return i


if len(argv) != 2:
    print("Usage: ./factors <file>")
    exit(98)
with open(argv[1]) as file:
    line = file.readline()
    while line != "":
        num = int(line)
        q = factorize(num)
        print("{}={}*{}".format(num, num//q, q))
        line = file.readline()
