#!/usr/bin/python3
from sys import argv


def factorize(num):
    if num % 2 == 0:
        return 2
    i = 3
    while num % i != 0:
        i += 2
        if i > num//2:
            return 1
    return i


if len(argv) != 2:
    print("Usage: ./factors <file>")
    exit(98)
with open(argv[1]) as file:
    line = file.readline()
    while line != "":
        num = int(line)
        q = factorize(num)
        print("{}={}*{}".format(num, num//q, q))
        line = file.readline()
