#!/usr/bin/python3
import sys


def factorize(num):
    list = [0, 0]
    if num % 2 == 0:
        list[0] = (num//2)
        list[1] = 2
        return list
    elif num % 3 == 0:
        list[0] = (num//3)
        list[1] = 3
        return list
    else:
        i=4
        while (num % i != 0):
            i += 1
        list[0] = (num//i)
        list[1] = i
        return list


if len(sys.argv) != 2:
    print("Usage: ./factors <file>")
    exit(98)
file_name = sys.argv[1]
with open(file_name) as file:
    line = file.readline()
    while line is not None and line != "":
        num = int(line)
        [p, q] = factorize(num)
        print("{:d}={}*{}".format(num, p, q))
        line = file.readline()
